### ISSUE TITLE
Penjelasan fungsi buttonForm

### ISSUE THREAD

**Issue by ImBobby** [sebastianusbara/edulab-training#18]
Di dalam `main.js` terdapat sebuah fungsi namanya `buttonForm` di mana isinya adalah

``` Javascript
buttonForm: function () {
    var $buttonForm     = $('.register .btn');
    var $registerForm   = $('.register');

        $registerForm.on ( 'click', '.btn', function() {
        $(this).toggleClass('btn--active btn--deactive');
    });
}
```

Tolong jelaskan tujuan fungsi itu dibuat

**Comment by sebastianusbara** [comment]
fungsi tersebut saya tulis karena sebelumnya form menggunakan button untuk memilih hari bimbingan, bukan dengan checklist dan lupa saya hapus. Fungsi tersebut sekarang sudah saya hapus mas.
